# -*- coding: utf-8 -*-
"""ms

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GRnJq-dTIABHbM7c-tlEAASm05ySVcN9
"""

import random
import numpy as np
import math

class minesweeper:
  def __init__(self, n, m):
    self.field = np.zeros([n, n])
    self.hidden = np.full((n, n), '▉')
    self.len = n
    self.end = False
    for i in range(m):
      x = random.randint(0, n-1)
      y = random.randint(0, n-1)
      while self.field[x][y] == -1:
        x = random.randint(0, n-1)
        y = random.randint(0, n-1)

      self.field[x][y] = -1
      if x+1 <= n-1 and self.field[x+1][y] != -1:
        self.field[x+1][y] += 1
      if x+1 <= n-1 and y-1 >= 0 and self.field[x+1][y-1] != -1:
        self.field[x+1][y-1] += 1
      if y-1 >= 0 and self.field[x][y-1] != -1:
        self.field[x][y-1] += 1
      if x-1 >= 0 and y-1 >= 0 and self.field[x-1][y-1] != -1:
        self.field[x-1][y-1] += 1
      if x-1 >= 0 and self.field[x-1][y] != -1:
        self.field[x-1][y] += 1
      if x-1 >= 0 and y+1 <= n-1 and self.field[x-1][y+1] != -1:
        self.field[x-1][y+1] += 1
      if y+1 <= n-1 and self.field[x][y+1] != -1:
        self.field[x][y+1] += 1
      if x+1 <= n-1 and y+1 <= n-1 and self.field[x+1][y+1] != -1:
        self.field[x+1][y+1] += 1

    self.disp(True)
  
  def disp(self, hidden):
    if hidden:
      for x in range(self.len):
        for y in range(self.len):
          if self.hidden[x][y] == -1:
            print('X', end=' ')
          elif self.hidden[x][y] == 0:
            print(' ', end=' ')
          elif self.hidden[x][y] == '▉':
            print('▉', end=' ')
          else:
            print(math.trunc(self.field[x][y]), end='  ')
        print('')
    else:
      for x in range(self.len):
        for y in range(self.len):
          if self.field[x][y] == -1:
            print('X', end=' ')
          elif self.field[x][y] == 0:
            print(' ', end=' ')
          else:
            print(math.trunc(self.field[x][y]), end=' ')
        print('')
    print('\n')      

  def select(self, y, x):
    zero = False
    self.hidden[x][y] = self.field[x][y]
    if self.field[x][y] == -1:
      self.lose()
      return
    if self.field[x][y] == 0:
      if x+1 <= self.len-1:
        if self.field[x+1][y] == 0 and self.hidden[x+1][y] == '▉':
          self.hidden[x+1][y] = self.field[x+1][y]
          self.select(x+1,y)
        else:
          self.hidden[x+1][y] = self.field[x+1][y]
      if x+1 <= self.len-1 and y-1 >= 0:
        if self.field[x+1][y-1] == 0 and self.hidden[x+1][y-1] == '▉':
          self.hidden[x+1][y-1] = self.field[x+1][y-1]
          self.select(x+1,y-1)
        else:
          self.hidden[x+1][y-1] = self.field[x+1][y-1]
      if y-1 >= 0:
        if self.field[x][y-1] == 0 and self.hidden[x][y-1] == '▉':
          self.hidden[x][y-1] = self.field[x][y-1]
          self.select(x,y-1)
        else:
          self.hidden[x][y-1] = self.field[x][y-1]
      if x-1 >= 0 and y-1 >= 0:
        if self.field[x-1][y-1] == 0 and self.hidden[x-1][y-1] == '▉':
          self.hidden[x-1][y-1] = self.field[x-1][y-1]
          self.select(x-1,y-1)
        else:
          self.hidden[x-1][y-1] = self.field[x-1][y-1]
      if x-1 >= 0:
        if self.field[x-1][y] == 0 and self.hidden[x-1][y] == '▉':
          self.hidden[x-1][y] = self.field[x-1][y]
          self.select(x-1,y)
        else:
          self.hidden[x-1][y] = self.field[x-1][y]
      if x-1 >= 0 and y+1 <= self.len-1:
        if self.field[x-1][y+1] == 0 and self.hidden[x-1][y+1] == '▉':
          self.hidden[x-1][y+1] = self.field[x-1][y+1]
          self.select(x-1,y+1)
        else:
          self.hidden[x-1][y+1] = self.field[x-1][y+1]
      if y+1 <= self.len-1:
        if self.field[x][y+1] == 0 and self.hidden[x][y+1] == '▉':
          self.hidden[x][y+1] = self.field[x][y+1]
          self.select(x,y+1)
        else:
          self.hidden[x][y+1] = self.field[x][y+1]
      if x+1 <= self.len-1 and y+1 <= self.len-1:
        if self.field[x+1][y+1] == 0 and self.hidden[x+1][y+1] == '▉':
          self.hidden[x+1][y+1] = self.field[x+1][y+1]
          self.select(x+1,y+1)
        else:
          self.hidden[x+1][y+1] = self.field[x+1][y+1]
    
    self.disp(True)
  
  def lose(self):
    self.disp(False)
    print('You Lose')
    self.end = True

game = minesweeper(10, 15)
while game.end == False:
  inp = input()
  inps = inp.split(' ')
  game.select(int(inps[0])-1, int(inps[1])-1)